version: "3.8"
services:
  wordpress:
    image: wordpress
    ports:
    - 8080:80
    links:
    - db:mysql
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
  mail:
    image: mailhog/mailhog
    ports:
    - 1025:1025
    - 8025:8025
