name: Test github action services

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    # Environment Variables
    env:
      MAIL_HOST: localhost
      MAIL_PORT: 25
      MAILHOG_API_PORT: 8025
      MAILHOG_API_URL: localhost
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      mailhog:
        image: mailhog/mailhog
        ports:
        - 25:1025
        - 8025:8025
        #env:
          #MH_HOSTNAME: mailhog.lokal
          #MH_API_BIND_ADDR: 0.0.0.0:8025
          #MH_SMTP_BIND_ADDR: 0.0.0.0:25

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Display listeningports
      run: |
        netstat -tulpen
        docker ps -a
        free
        cat /proc/cpuinfo
        sudo iptables -L

    - name: Validate mailhog availability - Call the mailserver api
      run: |
        curl -i http://localhost:8025/api/v2/messages

    - name: Validate mailhog availability - Telnet to the mailserver
      run: |
        chmod +x ./.github/scripts/test_mailhog.sh
        ./.github/scripts/test_mailhog.sh


    - name: Validate mailhog availability - Call the mailserver api
      run: |
        curl -i http://localhost:8025/api/v2/messages

    - name: Validate mailhog availability - Call the mailserver api
      run: |
        curl -i -X DELETE http://localhost:8025/api/v1/messages
        curl -i http://localhost:8025/api/v2/messages
